### ISSUE TITLE
`home` URL is broken?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/multiprocess-feedstock#19]
The [`home` url]( https://github.com/conda-forge/multiprocess-feedstock/blob/d79ddbbf127772b65b70167f26c859238fe153b3/recipe/meta.yaml#L36 ) appears to give a 404.

**Comment by jakirkham** [comment]
On PyPI, they just link back to PyPI. So maybe that can be used?

https://pypi.org/project/multiprocess/

**Comment by jschueller** [comment]
done

**Comment by jakirkham** [comment]
PR ( https://github.com/conda-forge/multiprocess-feedstock/pull/29 ) should update the feedstock README as well
